### PR TITLE
Copr remove f38

### PR DESCRIPTION
**Pull request by LukeShortCloud**

### CODE REVIEW

**Comment by LukeShortCloud** [comment]
I noticed that the `mesa` source RPM failed to upload.

```
Run copr-cli build gaming --exclude-chroot fedora-38-aarch64 --exclude-chroot fedora-38-i386 --exclude-chroot fedora-38-x86_64 ~/rpmbuild/SRPMS/mesa-*.src.rpm

Something went wrong:
Error: Bad request parameters: {'exclude_chroots': ["'fedora-3[8](https://github.com/playtron-os/rpm-specs-gaming/actions/runs/9471518783/job/26094906575#step:11:9)-i386', 'fedora-38-x86_64', 'fedora-38-aarch64' are not valid choices for this field."]}
```
https://github.com/playtron-os/rpm-specs-gaming/actions/runs/9471518783/job/26094906575

I updated all of the GitHub Actions workflows to (1) remove any excludes for the end-of-life Fedora 38 chroots and (2) also made sure that all builds are now using Fedora 40. Most were on Fedora 38. One was on Fedora 39. None were using Fedora 40.

**Comment by LukeShortCloud** [comment]
Early today, I also noticed that workflows were not working for non-main branches. I switched the logic to use

```
branches-ignore:
  - main
```

and now it works! I verified by temporarily setting the default branch to `copr-remove-f38` (from this PR) and sending a dummy commit.

https://github.com/playtron-os/rpm-specs-gaming/actions/runs/9476340198

**Comment by LukeShortCloud** [comment]
For `mesa`, as a short-term workaround (I need the package updated for testing purposes), I manually uploaded the source RPM and kicked off a build here: https://copr.fedorainfracloud.org/coprs/playtron/gaming/build/7604356/

**Review by ShadowApex — APPROVED** [review]
LGTM!

**Comment by LukeShortCloud** [comment]
Thanks a bunch!

**Pull request merged**
